image: gruunday/opencv-python3:latest

before_script:
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$PROD_SSH_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

test:
    stage: test
    script:
        - pip3 install -r requirements.txt
        - python3 -V
        - cd src/ && mv default_config.py config.py 
        - coverage run --source=. -m unittest discover -v
        - coverage report -m

deploy:
    stage: deploy
    script:
        - cd src/
        - rsync -r -v -e ssh . greenday@panoptes.xyz:/home/greenday/prod/
        - chmod +x deploy 
        - ssh greenday@panoptes.xyz DBNAME=$DBNAME DBPASSWORD=$DBPASSWORD DBHOST=$DBHOST DBUSER=$DBUSER DBPORT=$DBPORT 'bash -s' < deploy
