image: gruunday/opencv-python3:latest

before_script:
    - pip3 install -r requirements.txt
    - python3 -V
    - cd src/ && mv default_config.py config.py 

test:
    stage: test
    script:
        - coverage run --source=. -m unittest discover -v
        - coverage report -m

build:
    stage: deploy
    script:
        - cat $PROD_SSH_KEY > deploy_key.pem
        - ssh -i deploy_key.pem greenday@panoptes.xyz DBNAME=$DBNAME << EOF 
            echo $DBNAME 
          EOF
