image: gruunday/opencv-python

before_script:
    - apt-get update && apt-get install -y python3
    - python3 -V 

test:
    script:
        - cd src/
        - coverage run --source=. -m unittest discover -v
        - coverage report -m
