image: gruunday/opencv-python

before_script:
    - pip3 install coverage
    - python3 -V 

test:
    script:
        - cd src/
        - coverage run --source=. -m unittest discover -v
        - coverage report -m
