image: gruunday/opencv-python3:latest

before_script:
    - pip3 install -r requirements.txt
    - python3 -V
    - cd src/ && mv default_config.py config.py 

test:
    script:
        - coverage run --source=. -m unittest discover -v
        - coverage report -m
