image: gruunday/opencv-python

before_script:
    - apt-get update && apt-get install -y python3
    - python3 -V 

test:
    script:
        - cd src/playground/
        - python3 hello-world.py 
     
