version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
    curart:
        restart: always
        build:
            context: .
        environment:
            DBUSER: ${DBUSER:-latest}
            DBPASSWORD: ${DBPASSWORD:-latest}
            DBHOST: ${DBHOST:-latest}
            DBNAME: ${DBNAME:-latest}
            DBPORT: 5432
        labels:
            - traefik.backend=upload
            - traefik.frontend.rule=Host:upload.dtom.dev
            - traefik.docker.network=proxy
            - traefik.port=8080
        networks:
            - internal
            - proxy
    traefik:
        image: traefik:1.5.4
        container_name: traefik
        restart: always
        ports:
            - "443:443"
            - "80:80"
        networks:
            - proxy
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/etc/containers/traefik/traefik.toml:/traefik.toml"
            - "/etc/containers/traefik/traefik.toml:/acme.json"
        labels:
            - "traefik.frontend.rule=Host:monitor.dtom.dev"
            - "traefik.port=8080"
